# Generated by Django 2.0.2 on 2018-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
